### ISSUE TITLE
nextflow.config defines script_dir path as script_dir = "${projectDir}/../repo/scripts/" but "repo" should either be mgs-workflow or a variable.

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-workflow#1]
https://github.com/naobservatory/mgs-workflow/blob/5da3ea8710ace7393fa597ad580c13ab3ab9c188/configs/index.config#L29

nextflow.config defines the `script_dir` path as `script_dir = "${projectDir}/../repo/scripts/"` but `repo` should either be a placeholder, `mgs-workflow`, or a variable that gets defined earlier. E.g.:
```
repo_dir = "mgs-worfklow"
script_dir = "${projectDir}/../{repo_dir}/scripts/"
```

**Comment by willbradshaw** [comment]
The user is responsible for setting their config file to point to the right places; as the developer I don't know what the repo directory will be called (mine is called "repo", yours is called "mgs-workflow") or where it will be relative to the launch directory.

That said, this specific instantiation of this issue will shortly become moot with the new version of the pipeline I'm currently finalizing.
