### ISSUE TITLE
EXTRACT_UNCONC_READS is too slow

### ISSUE THREAD

**Issue by willbradshaw** [naobservatory/mgs-workflow#10]
The `EXTRACT_UNCONC_READS` process is often limiting for large runs. Need to rework it to be more efficient.

**Comment by mikemc** [comment]
Is this process simply taking a set of read ids specified by `id_file` and getting those reads from the fastq files in `reads_unconc`? If so, then I'm guessing we can do this much faster with `seqtk subseq` instead (https://github.com/lh3/seqtk). This can be done streaming from S3, e.g.

```
for () ; do
  aws s3 cp READS_1.fastq.gz - | seqtk subseq - READS.LIST > OUT_1.fastq
  aws s3 cp READS_2.fastq.gz - | seqtk subseq - READS.LIST > OUT_2.fastq
done
```

**Comment by mikemc** [comment]
If the read-id input already has the needed format of one read id per line, then I think the following should work:
```sh
        inp0="!{id_file}"
        inp1="!{reads_unconc[0]}"
        inp2="!{reads_unconc[1]}"
        outp1="!{sample}_bowtie2_mapped_unconc_1.fastq.gz"
        outp2="!{sample}_bowtie2_mapped_unconc_2.fastq.gz"
        seqtk subseq $inp1 $inp0 | gzip > $outp1
        seqtk subseq $inp2 $inp0 | gzip > $outp2
```

**Comment by willbradshaw** [comment]
Thanks @mikemc, I've tried implementing your suggestion in the dev branch and will close this if that turns out to fix the problem.

**Comment by willbradshaw** [comment]
Confirmed @mikemc's solution resolved this, EXTRACT_UNCONC_READS is no longer a major runtime bottleneck.
