### ISSUE TITLE
arb-silva data is not available anympore.

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-workflow#2]
The download URLs for ribosomal RNA return 404.

```
https://www.arb-silva.de/fileadmin/silva_databases/release_138.1/Exports/SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz
https://www.arb-silva.de/fileadmin/silva_databases/release_138.1/Exports/SILVA_138.1_LSURef_NR99_tax_silva.fasta.gz
```

When visiting arb-silva.de's archive it shows up as empty: https://www.arb-silva.de/index.php?id=272 I checked the internet archive and the archive still had content some time ago. I will contact arb-silva about this but @willbradshaw let me know if you know of an easy replacement for this data.

**Comment by willbradshaw** [comment]
It's showing up for me:
https://www.arb-silva.de/no_cache/download/archive/release_138_1/Exports/

**Comment by simonleandergrimm** [comment]
Yes, because they fixed it right after I contacted them 🚀

> Dear Simon,
> 
> there are currently some issue with our hosting environment which our IT department could not yet resolve. I am not sure if that also caused the archive issue or if that was related to some maintenance today. I was able to restore the access to the archive, though.
> 
> Best regards,
> Jan
>

**Comment by simonleandergrimm** [comment]
Closing this issue given that it's working again.

**Comment by simonleandergrimm** [comment]
Closing this issue given that arb-silva fixed it.
