### ISSUE TITLE
Is importing data into S3 in-scope for this project?

### ISSUE THREAD

**Issue by jeffkaufman** [naobservatory/mgs-workflow#25]
One place where we're still using the v1 pipeline is to import data into S3.  This includes the hacky [import-accession.sh](https://github.com/naobservatory/mgs-pipeline/blob/main/import-accession.sh) as well as [mgs-restricted](https://github.com/naobservatory/mgs-restricted/)`/import-*.sh` for several of our partners.  These are just linux scripts and don't use Nextflow.

@willbradshaw are you thinking these are out of scope for this project and should stay in mgs-pipeline / mgs-restricted?

**Comment by willbradshaw** [comment]
I do think of this as out-of-scope for the core workflow, and honestly an awkward fit for a pipeline-based approach in general. I think it should be the user's responsibility to get the data into a suitable state to run the pipeline (though I don't think that should necessarily mean it has to be in our S3 in a very specific structure).

That said, I'm not opposed to including some auxiliary scripts in the repo that users could use to do this in common use cases.
