### ISSUE TITLE
Respect given memory parameter in BBTools processes

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#36]
See https://github.com/naobservatory/mgs-workflow/issues/29 for a description and illustration of the issue. The fix involves generating the correct bbtools/java memory parameter string from the workflow's `task.memory` parameter.

Applies to 'RUN:DEDUP:CLUMPIFY_PAIRED' and other processes that use BBTools scripts

**Comment by willbradshaw** [comment]
Similar issue also applies to other BBTools processes (grep for BBTools
label or Xmx memory string

**Comment by mikemc** [comment]
@willbradshaw two clarification questions that will help me figure this out:

First, I notice sometimes we have `params.mem` appearing in the process definition, e.g. 

```java
process KRAKEN {
    label "Kraken2"
    cpus 16
    memory "${params.mem}"
    input:
```

can you explain what that is doing and if it is related to `task.memory`?

Second, to help me determine how to translate the `resources.config` memory parameters to those needed by Java (e.g. 30g, 1600m), could you clarify where the format used in the resources.config for memory (e.g. "32.GB") comes from or what strings are allowed? (e.g. is "32.5GB" allowed?)

Third, is there an example you can point to where the `resources.config` memory parameters are being used (if the KRAKEN instance above is not one)? If they aren't being used at all yet, then perhaps it would make sense to  require that they are specified in the java format to avoid needing to translate from "32.5GB" to "32500m"

**Comment by willbradshaw** [comment]
> can you explain what that is doing and if it is related to task.memory?

`params.mem` here is an arbitrary value that's being passed to the process when the module is imported (using the `addParams` statement). I've called it `mem` in this case but I could call it anything and it would still work.

`task.memory` is a specific value that's declared via the [`memory` process directive](https://www.nextflow.io/docs/latest/process.html#memory) and specifies the amount of memory allocated by Nextflow to the process. In this case, `params.mem` is being used to allow the value of `task.memory` to be configured when the module is imported.

> Second, to help me determine how to translate the resources.config memory parameters to those needed by Java (e.g. 30g, 1600m), could you clarify where the format used in the resources.config for memory (e.g. "32.GB") comes from or what strings are allowed? (e.g. is "32.5GB" allowed?)

Good question, I had to look this up. I think [this](https://www.nextflow.io/docs/latest/script.html#implicit-classes-memoryunit) is the relevant part of the Nextflow documentation, which states that "You can create a memory unit by adding a unit suffix to an integer, e.g. 1.GB". So I think we can safely assume it will be an integer value, with a 1:1 mapping between unit suffixes in nextflow and those in Java.

> Third, is there an example you can point to where the resources.config memory parameters are being used (if the KRAKEN instance above is not one)?

As I understand it, it's being used in every process, including KRAKEN; it specifies the amount of memory that process is allowed to use. The problem in the BBTools processes isn't that the memory parameters aren't being used. Rather, it's that the process is only allocated the amount of memory specified by the relevant `memory` directive, but is trying to claim more than that and so failing.

**Comment by mikemc** [comment]
Thanks @willbradshaw , this is very helpful!

**Comment by mikemc** [comment]
I looked to see how https://github.com/nf-core/mag handles this issue and found this example,

```sh
    bbnorm.sh \\
        $input \\
        $output \\
        $args \\
        threads=$task.cpus \\
        -Xmx${task.memory.toGiga()}g \\
        &> ${prefix}.bbnorm.log
```

[link](https://github.com/nf-core/mag/blob/aac4962a09b1815c27ca88bb8bf6f64e7b78505f/modules/nf-core/bbmap/bbnorm/main.nf#L34)

Apparently the Nextflow DSL [defines a MemoryUnit class](https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/main/nextflow/util/MemoryUnit.groovy) that has methods to help with the conversion, including `toGiga()` which is used above.

So my plan is to simply swap in `-Xmx${task.memory.toGiga()}g` everywhere. I'll do this once I get the full pipeline working for testing purposes.

**Comment by jtjvanlunenburg** [comment]
Memory config can be unlimited, e.g. `mem = 0`, in which case `task.memory` is a null object and there is no `toGiga` method (nor a `.giga` prop)? How would you work around this scenario?

**Comment by willbradshaw** [comment]
@mikemc did you end up getting any further with this? Would you like me to include it in the list of issues for Harmon to work on in Q4?

**Comment by mikemc** [comment]
I consider the fix I describe above, implemented in https://github.com/naobservatory/mgs-workflow/commit/89b2c75c4dd503f4ffbde0388bc68b16c0d9d4c4, as fixing the issue and is what @evanfields has been using. I think it's an improvement over hard-setting the memory. 

Regarding @jtjvanlunenburg 's question, I guess you might want to handle this, but I'm guessing making the workflow support setting unlimited memory should be its own new issue and not block fixing the immediate issue.

**Comment by willbradshaw** [comment]
Cool, I'll add it to the list. I agree handling unlimited memory isn't a major priority.

**Comment by willbradshaw** [comment]
This is now implemented.
