### ISSUE TITLE
Math in footnote 8 doesn't render correctly.

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-workflow#39]
<img width="1082" alt="image" src="https://github.com/naobservatory/mgs-workflow/assets/58591538/9a620d1c-96d1-4039-a896-de529536aadf">

**Comment by simonleandergrimm** [comment]
Specifically, Kraken-unassigned read pairs are classed as human-viral if, for either read in the pair, $S/ln(L) >= T$, where $S$ is the best-match Bowtie2 alignment score for that read, $L$ is the length of the read, and $T$ is the value of params.bt2_score_threshold specified in the config file.

**Comment by mikemc** [comment]
@simonleandergrimm could you share where is the "here" that it is rendering correctly? (that would help figure out the difference between it working vs not working). 

I wonder if [github markdown's mathjax support](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) doesn't work in footnotes, or if something like [this old pandoc bug](https://github.com/jgm/pandoc/issues/2881) is happening in github markdown

**Comment by simonleandergrimm** [comment]
In the comment itself:

> It renders correctly here:

Specifically, Kraken-unassigned read pairs are classed as human-viral if, for either read in the pair, 
, where 
 is the best-match Bowtie2 alignment score for that read, 
 is the length of the read, and 
 is the value of params.bt2_score_threshold specified in the config file.

**Comment by willbradshaw** [comment]
In this case I think it's fine if I just don't use MathJax and show the equations in plaintext. I'll do that now.
