### ISSUE TITLE
main.config is pointing to `ref/adapters.fa`, but the file is called `ref/adapters.fasta`

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-workflow#4]
https://github.com/naobservatory/mgs-workflow/blob/a18c5855ba0f7727007ab90dbf0940716e3f1d3f/configs/main.config#L26C2-L26C50

See file `ref/adapters.fasta`:
https://github.com/naobservatory/mgs-workflow/blob/master/ref/adapters.fasta

@willbradshaw Leave a thumbs-up if this is a mistake; this is an easy fix.

**Comment by willbradshaw** [comment]
Fixed in [dev branch](https://github.com/naobservatory/mgs-workflow/tree/dev).
