### ISSUE TITLE
QC on undefined channel in RAW workflow (only when subsampling reads)

### ISSUE THREAD

**Issue by evanfields** [naobservatory/mgs-workflow#42]
In https://github.com/naobservatory/mgs-workflow/blob/master/subworkflows/local/raw/main.nf#L26 line `qc_ch = QC(trunc_ch)`: `trunc_ch` is undefined and `QC` is repeated a few lines down. Will suggests deleting the line and requested an issue, so here we are.

**Comment by willbradshaw** [comment]
Thanks, fixed in dev branch, will push soon!
