### ISSUE TITLE
Consider moving scripts from bin/ to their corresponding module

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#47]
For example, `process_bowtie2_sam.py` belongs to the `processBowtie2Sam` module; it would be helpful organizationally and more in line with the idea of modules being self contained to have this script within `modules/local/processBowtie2Sam`. 

https://www.nextflow.io/docs/latest/module.html#module-binaries discusses one way to do this, but has a "Note" that makes me unsure if we can use this approach with our workflow.

> Modules can define binary scripts that are locally scoped to the processes defined by the tasks.
> 
> To enable this feature, enable the following flag in your pipeline configuration file:
> ```
> nextflow.enable.moduleBinaries = true
> ```
> The binary scripts must be placed in the module directory names `<module-dir>/resources/usr/bin`:
> 
> ```
> <module-dir>
> |── main.nf
> └── resources
>     └── usr
>         └── bin
>             |── your-module-script1.sh
>             └── another-module-script2.py
> ```
> Those scripts will be made accessible like any other command in the task environment, provided they have been granted the Linux execute permissions.
> 
> Note
> 
> This feature requires the use of a local or shared file system for the pipeline work directory, or [Wave containers](https://www.nextflow.io/docs/latest/wave.html#wave-page) when using cloud-based executors.

**Comment by willbradshaw** [comment]
Yes, this should work -- we use Wave containers.

**Comment by willbradshaw** [comment]
I've verified this works on [my current feature branch](https://github.com/naobservatory/mgs-workflow/tree/will-virus-db-public).

Changing scripts in the base `bin` directory seems to break Nextflow caching, forcing a full resume of the pipeline. Assuming changing scripts in module-specific `bin` directories doesn't do this, this would be a compelling reason to make this change sooner rather than later.

**Comment by willbradshaw** [comment]
This is now done.
