### ISSUE TITLE
Consider marking duplicates in bowtie2 HV output with `samtools markdup`

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#48]
We can use samtools to use the HV alignments to check for duplicates and add a flag (1024). This page https://www.htslib.org/algorithms/duplicate.html gives information and usage. This would give us an additional alignment-based measure of duplication. Since we can always ignore the 1024 flag, the only cost is the time to add this extra step. However, since it would only be running on the HV alignments, it should be very quick.

@willbradshaw if you think this is a good idea I can suggest a samtools pipechain to do it. (I'm currenting testing using `samtools markdup` to look at duplication in PMMoV reads)

**Comment by willbradshaw** [comment]
Sure sounds like a good idea to me, thanks!

**Comment by mikemc** [comment]
In testing this out, I realized that it won't plug into the HV workflow as easily as I hoped, because the first step in the pipechain (a call to `samtools collate` requires having the `SQ` lines (which identifies and give the lengths of the reference sequences). The HV sam files don't have the SQ header lines due to the `--no-seq` flag in 

https://github.com/naobservatory/mgs-workflow/blob/f534a8625864cfcc54525b1d2b481c08056fffd5/subworkflows/local/hv/main.nf#L55

I'm guessing @willbradshaw added this to reduce the file size of the SAM output. I briefly tried to find a workaround that wouldn't require removing the `--no-seq` flag, e.g. by specifying the reference file later in `samtools collate` (didn't seem to work) or adding a `samtools view` step to try to add them back in, but haven't had success yet and need to move on for now.

But below I give the nextflow process code for doing this on a bowtie2 output that does have the SQ header lines.

---

Here's the shell code that you could wrap in the shell block of a process: (the comments are just to help follow along)

```sh
# input:
#     val(sample)
#     path(bowtie2_sam)
# Put the below in a shell block delimited by three single quotes
samtools collate -@ !{task.cpus} -O -u !{bowtie2_sam} \
  | samtools fixmate -@ !{task.cpus} -m -u - - \
  | samtools sort -@ !{task.cpus} -u - \
  | samtools markdup -@ !{task.cpus} -t --duplicate-count \
    -f !{sample}_markdup_stats.txt - !{sample}_markdup.sam
```

Some notes about the output: Optional SAM fields added by samtools that get added to the end of the optional SAM fields from bowtie2 include

- "MC:Z:151M	ms:i:5118" --- The "MC" and "ms" tags are added by `samtools fixmate`; these are the CIGAR string and quality statistic of the mate, which are needed by `samtools markdup`
- "do:Z:VH01619:67:AAFY5LGM5:1:1104:57485:24797" -- The "do" tag is added to duplicates and points to the "original" read pair (the read pair with the best overall quality)
- dc:i:2 --- added to the original read pairs, records the copy number. Analogous to "copies=2" in clumpify output

Besides these optional fields, some header comment lines (starting with "@") get added by samtools to track the samtools commands that were run

Additional notes about the call to `samtools markdup`

- the `-t` and `--duplicate-count` options are needed to add the "do" and "dc" flags below
- `-r` option would remove duplicates (in which case the `-t` field becomes useless)
- `-d ???` sets the distance for optical duplicate marking; currently it's not set, which means there is no attempt to distinguish optical duplicates from PCR duplicates.
- `-l ???` sets the max read length. The default is 300, which seems generally fine for us. I don't know if there's a significant speed advantage to lowering it to the min possible (e.g. 151 for the 2x150 sequencing we usually have), but already this is quite fast

Misc notes

- I don't really understand the difference between `--mode t` (default) and `--mode s`, described in the above docs page. It sounds like it shouldn't make a big difference, and it seems to make no difference in my PMMoV testing.
- this should be quite fast when run on just HV reads; using `!{task.cpus}` may be overkill  --- in my testing on ~30K PMMoV aligned read pairs, using 1 versus 6 cpus has a negligible difference --- but I guess it shouldn't hurt
