### ISSUE TITLE
Implement duplication analysis

### ISSUE THREAD

**Issue by willbradshaw** [naobservatory/mgs-workflow#56]
One of two new capabilities I'd like to add to our core pipeline is analysis of duplication levels (and/or library complexity). I basically don't believe the BLAST numbers and would really like to replace them with something smarter. There are several ways of doing this we could try, and it's possible we'll want to do it multiple ways. Will probably want input from @mikemc on the best way to approach this.

**Comment by mikemc** [comment]
Happy to help here, I'd be keen to take some time to talk this out with you and @harmonbhasin
