### ISSUE TITLE
Change repo name to mgs-pipeline-v2?

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#6]
When looking at the list of NAO repos, I always find it hard to remember which of 'mgs-workflow' or 'mgs-pipeline' is which. @jeffkaufman uses 'v1 pipeline' and 'v2 pipeline' to distinguish them. Perhaps we should put that right in the repo name? (I also think 'pipeline' is a good description of what this is, since it is intended to be run with minimal user interaction/customization, whereas I generally use 'workflow' for something more interactive)

Edit: Perhaps 'workflow' here is because of the [its use as a technical term in Nextflow](https://www.nextflow.io/docs/latest/workflow.html), though interestingly the Nextflow docs also use 'pipeline' as a more general/generic term e.g. [here](https://www.nextflow.io/docs/latest/sharing.html)

**Comment by jeffkaufman** [comment]
This is fine with me, though I think it's likely that if we don't rename them you'll get used to the current names, and then other people won't have to go through this confusion because soon we'll stop interacting with `mgs-pipeline` and only interact with `mgs-workflow`?

**Comment by willbradshaw** [comment]
I don't have strong feelings here.

**Comment by willbradshaw** [comment]
Honestly at this point I might suggest we migrate `mgs-pipeline` to `mgs-pipeline`-old or similar sometime this quarter, then migrate this to `mgs-pipeline`. Especially since we might at some point want to increment to v3+.

@jeffkaufman wdyt?

**Comment by jeffkaufman** [comment]
I think it's fine to have `-v2` (and later `-v3`) suffixes in repos in cases where it's a major shift in structure.  What about:

* Move `mgs-pipeline` to `mgs-pipeline-v1`, update the documentation to say it's deprecated, and move anything in it that we are still using to `mgs-restricted`.
* Move `mgs-workflow` to `mgs-pipeline-v2`

**Comment by willbradshaw** [comment]
Are you proposing moving to a new repo entirely when we move to v3?

What's your objection to my proposal? I assume you don't like it since you're counter-proposing, but not sure why.

**Comment by jeffkaufman** [comment]
The main reason I don't like moving `mgs-workflow` to `mgs-pipeline` is that things that currently point to the latter would then be confusing.  And also that they don't have a shared git history?  But not super strong feelings.

**Comment by willbradshaw** [comment]
I don't think this is likely to happen any time soon, and I'd like to clean up our backlog of stale issues, so I'm closing this.
