### ISSUE TITLE
Switch to new "core_nt" database for blast steps?

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#62]
The Blast web interface recently switched to a new default database, "core_nt". [info](https://ncbiinsights.ncbi.nlm.nih.gov/2024/07/18/new-blast-core-nucleotide-database/)

> Effective August 2024, core_nt will become the default 
> 
> Interested in faster nucleotide [BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi?utm_source=ncbi_insights&utm_medium=referral&utm_campaign=blast-core-nt-20240717) searches with more focused search results? As [previously announced](https://ncbiinsights.ncbi.nlm.nih.gov/2022/11/17/re-evaluating-blast-nucleotide-nt/?utm_source=ncbi_insights&utm_medium=referral&utm_campaign=blast-core-nt-20240717), NCBI has been re-evaluating the BLAST nucleotide database (nt) to make it more compact and more efficient. Thanks to your feedback, NCBI’s BLAST is excited to introduce the core nucleotide database (core_nt), an alternative to the default nt database that contains better-defined content and is less than half the size. 
> 
> Benefits of BLAST core_nt over nt
> - Enables faster searches  
> - Returns similar top results for most searches 
> - Reduces redundancy for some highly represented organisms 
> - Allows easier download and requires less storage space for database download for standalone BLAST

I'm wondering if using core_nt would give more reliable blast results at lower computational overhead.

**Comment by willbradshaw** [comment]
I have no objection. @jeffkaufman?

**Comment by jeffkaufman** [comment]
In my manual testing, I agree `core_nt` seems to work well.

**Comment by willbradshaw** [comment]
Merged into master on latest release.
