### ISSUE TITLE
Reintroduce grouping for deduplication

### ISSUE THREAD

**Issue by harmonbhasin** [naobservatory/mgs-workflow#65]
While working on #60, we decided to remove concat_gzipped, which was combining all samples from the same library. While this functionality will still be need for deduplication, it's currently not being used and is super slow. For now, we're not going to prioritize this, but we will need to think about where we'll want to reintroduce this functionality into the pipeline.

**Comment by willbradshaw** [comment]
Merged into master on latest release.
