### ISSUE TITLE
Plan for getting mgs-workflow to take in Nanopore data.

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-workflow#69]
After a discussion with @jeffkaufman, this is how I would go about getting mgs-workflow to take in ONT long-read data.

### Process

1. Adapt the pipeline to optionally take in single-read data.
2. Once that is complete, finetune processes to take in long-read data, or add processes for long-read data.

### Branch structure

For creating the single-read run option, I would work through `run.nf` process by process, checking the output of the single-read run step by step. Once I'm happy with the new code, I'll 

- cherry-pick commits from a local dev branch into a `simon-new-feature-branch`, 
- check that it's working, and 
- create a pull request into `dev`. 

Each pull request will be focused on adapting a specific subworkflow or complex process.

### Next steps

As a first step, I will adapt `RAW` to optionally take in single-read data and will send a PR into `dev` to Will.

@willbradshaw let me know if this sounds good to you. @jeffkaufman and I thought it'd be best to pull directly into `dev`, as this stops us from having a huge final pull request (e.g.,`single-read-dev` into `dev`), that contains changes to the entire pipeline.

Also, please let me know if you think an entirely new workflow would make more sense than adapting `run.nf` (I think this will become clearer as I go through the actual work of adapting the workflow).

**Comment by simonleandergrimm** [comment]
@willbradshaw was skeptical that adding the single-read version of the pipeline bit by bit to `dev` would be bad, as `dev` should be fully functional. Instead, I will for now work with `single-read-dev`, create PRs for amended subworkflows that pull into that branch and get them reviewed and approved by @harmonbhasin . Once `single-read-dev` is ready, I can create a PR into `dev` and have it reviewed by @willbradshaw

**Comment by jeffkaufman** [comment]
@simonleandergrimm @willbradshaw maybe I wasn't clear enough on what I was proposing.  I agree we should keep `dev` functional at all times for all its documented usecases, but I think it's also ok if there are times when there is new functionality merged to `dev` that is isn't active yet.

(Long-running development branches that get merged later is something I've repeatedly seen work out very poorly as a software engineering approach, and I'd be happy to talk more about why I don't think this would be a good choice for us.)

**Comment by simonleandergrimm** [comment]
> @simonleandergrimm each PR would keep dev working for paired end reads, right?

Yeah I plan to test this each time before making a PR.

**Comment by willbradshaw** [comment]
This is in active development and doesn't currently seem like a great fit for an issue. I'm going to close this; @simonleandergrimm feel free to add other more specific issues for Nanopore stuff as they come up.
