### ISSUE TITLE
Possibly erroneous comment above process BOWTIE2_INDEX_REFERENCES

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#7]
https://github.com/naobservatory/mgs-workflow/blob/a18c5855ba0f7727007ab90dbf0940716e3f1d3f/workflows/index.nf#L170

It looks like this comment was copied from the comment above process BOWTIE2_INDEX_HUMAN (step 2.2b) and not modified.

**Comment by willbradshaw** [comment]
Rendered moot through restructuring in [dev branch update](https://github.com/naobservatory/mgs-workflow/tree/dev).
