### ISSUE TITLE
Implement an end-to-end test using nf-test

### ISSUE THREAD

**Issue by harmonbhasin** [naobservatory/mgs-workflow#88]
Using this issue as a place to write down progress/issues that have come up with my attempt to setup an end-to-end testing suite using [nf-test](https://www.nf-test.com/).

The most important thing I've come across is that [we can't use s3 paths](https://github.com/askimed/nf-test/issues/78).

**Comment by willbradshaw** [comment]
@harmonbhasin is this done now? If so can you close?

**Comment by harmonbhasin** [comment]
@willbradshaw this is done, thanks!
