### ISSUE TITLE
Institute a changelog?

### ISSUE THREAD

**Issue by mikemc** [naobservatory/mgs-workflow#9]
I would find it helpful to have a list of changes as they affect me as a user of the pipeline output. An example is that in the newest runs, output is stored in "output/" rather than "output/results", and "hv_hits_putative_filtered.tsv.gz" is now gzipped. One way to do this is to start updating a [NEWS.md](https://r-pkgs.org/other-markdown.html#sec-news) file to record user-affecting changes (possibly it would make sense to start semantic versioning, but dates and/or short-hashes could do).

**Comment by jeffkaufman** [comment]
Another option would be to use code reviews.  Will could make changes as PRs, and send them to you for review.  This would have the additional benefit of you understanding more how the pipeline worked.

**Comment by mikemc** [comment]
Code reviews could separately be a good idea, but I still think having a plain-english summary of user-facing changes will be invaluable for anyone who wants to work with the results of the pipeline, and it will be easier for the person making the changes to at least draft these.

**Comment by willbradshaw** [comment]
I agree a changelog would be good. I don't think code reviews would substitute for this.

**Comment by willbradshaw** [comment]
Implemented [here](https://github.com/naobservatory/mgs-workflow/blob/master/CHANGELOG.md).
